#! /bin/bash
num=( "$@" )
total_num=${#num[@]}
sum=0
for (( i=1; i<total_num+1; i++ ));
do
   sum=$((sum+num[i-1]))
done

echo -n "average of the $total_num numbers is: "
echo "$sum / $total_num" | bc
